version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
  - dependency-name: serverless
    versions:
    - 2.21.1
    - 2.22.0
    - 2.23.0
    - 2.25.1
    - 2.25.2
    - 2.27.0
    - 2.27.1
    - 2.28.0
    - 2.28.3
    - 2.28.6
    - 2.28.7
    - 2.29.0
    - 2.30.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: ts-loader
    versions:
    - 8.0.14
    - 8.0.15
    - 8.0.16
    - 8.0.17
  - dependency-name: "@types/aws-lambda"
    versions:
    - 8.10.71
  - dependency-name: fast-csv
    versions:
    - 4.3.6
  - dependency-name: exceljs
    versions:
    - 4.2.0
  - dependency-name: serverless-webpack
    versions:
    - 5.3.5
