service:
  name: CsvParserEditor

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs10.9

functions:
  ParseCsvFiles:
    handler: ParseCsvFiles.handler
